name: Check Commit Messages(s)

# Get the repository with all commits to ensure that we can
# analyze all of the commits contributed via the Pull Request.

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: git-rev-list
      run: git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

    - name: check-commits.sh
      id: check_out
      run: |
        err=0
        pwd
        while read hash subj
        do
          echo "Checking: $hash (\"$subj\")"
          git show -s --format=%B $hash | .github/scripts/commit-msg-check.pl
          if test $?
          then
            $err=1
          fi
        done <<< $(git rev-list --oneline ${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}})

        if test $err
        then
          exit 2
        fi
