name: Set issue date

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  set-issue-date:
    runs-on: ubuntu-latest

    steps:
      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.PROJECT_PAT }}
          ORGANIZATION: ac000
          PROJECT_NUMBER: 9

        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              user(login: $org) {
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2FieldCommon {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER >project_data.json

          #echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >>$GITHUB_ENV
          #echo 'DATE_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name == "Created at") | .id' project_data.json) >>$GITHUB_ENV
          echo 'PROJECT_ID='$(jq '.data.user.projectV2.id' project_data.json) >>$GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.user.projectV2.fields.nodes[] | select(.name == "Created at") | .id' project_data.json) >>$GITHUB_ENV

      # Needed to get the issue's Global ID
      - name: Add issue to project
        env:
          GH_TOKEN: ${{ secrets.PROJECT_PAT }}

        run: |
          if [ "${{ github.event_name }}" = "issue" ]; then
            ITEM_ID=${{ github.event.issue.node_id }}
          else
            ITEM_ID=${{ github.event.pull_request.node_id }}
          fi

          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $item:ID!) {
              addProjectV2ItemById(
                input: {
                  projectId: $project, contentId: $item
                }) {
                  item {
                    id
                  }
                }
              }' -f project=$PROJECT_ID -f issue=$ITEM_ID --jq '.data.addProjectV2ItemById.item.id')"
          echo 'ITEM_ID='$item_id >>$GITHUB_ENV

      - name: Set issue date
        env:
          GH_TOKEN: ${{ secrets.PROJECT_PAT }}

        run: |
          if [ "${{ github.event_name }}" = "issue" ]; then
            DATE=${{ github.event.issue.node_id }}
          else
            DATE=${{ github.event.pull_request.node_id }}
          fi

          gh api graphql -f query='
            mutation(
              $project: ID!
              $item: ID!
              $date_field: ID!
              $date: Date!
            ) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $project
                  itemId: $item
                  fieldId: $date_field
                  value: {
                    date: $date
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
            }' -f project=$PROJECT_ID -f item=$ITEM_ID -f date_field=$DATE_FIELD_ID -f date=$DATE
