name: Tester

on:
  issues:
    types: [opened]

env:
  PR_STALE_DAYS: 1  # 180
  PR_CLOSE_DAYS: 2  # 90
  PR_TOTAL_DAYS:

jobs:
    tester:
      runs-on: ubuntu-latest

      steps:
        - name: Calculate
          run: PR_TOTAL_DAYS=$(($PR_STALE_DAYS+$PR_CLOSE_DAYS))

        - name: Display
          run: echo "PR_TOTAL_DAYS = $PR_TOTAL_DAYS"
